### PR TITLE
Complete redesign of the Top.gg API Documentation

### PR DESCRIPTION
**Pull request by bchurton**
This PR contains a **complete** redesign of the Top.gg API documentation.

It:
- Merges several pre-existing PRs, including some that are years old
- Redesigns the documentation using a modern Tailwind theme and replaces the stolen Apollo theme.
- Rewrites several parts to be more beginner-friendly, and makes some sections more consistent.

View a preview: https://docs-bchurton.vercel.app/

### CODE REVIEW

**Comment by kkrypt0nn** [comment]
LGTM 🚜

**Review by bchurton — COMMENTED** [review]
Credits: @bwrbur

**Comment by jpbberry** [comment]
This looks awesome. And I hate to be cynical, but I worry about the implications of creating a website from scratch meaning this repository would be in charge of maintaining, especially with how slow the repository is with approvals, there’s an advantage to having the site and theme made by another dedicated library.

**Comment by pixxies** [comment]
Please don't request reviews from Veld. Thank you! 🙏

**Comment by bchurton** [comment]
> Please don't request reviews from Veld. Thank you! 🙏

Was auto-done by Github, not sure why but was not intentionally done from my end

**Comment by jpbberry** [comment]
> Please don't request reviews from Veld. Thank you! 🙏

The CODEOWNERS auto requests veld

**Comment by bchurton** [comment]
Closed, PR caused a war in #topgg-api channel 😄

**Pull request closed without merging**
