### PR TITLE
Rework Python library examples

### PR DESCRIPTION
**Pull request by shivaco**
This PR reworks the examples in the official Python library documentation to exclude and work without discord.py cogs.

### CODE REVIEW

**Comment by iiLearner** [comment]
are you still using one file for everything?

**Comment by EEKIM10** [comment]
I don't see why this is needed personally, what's the issue with cogs?

**Comment by shivaco** [comment]
The main reason is because cogs are unnecessary in terms of simply getting the module to work. Additionally, cogs are exclusive to the commands extension, which is not always used by developers.

**Comment by EEKIM10** [comment]
Understandable.

Also line #41-43 of python.mdx - This would raise an error, as you're trying to start the loop before you've defined the function.

**Comment by shivaco** [comment]
There we go, thanks for the notice!

**Pull request merged**
