### PR TITLE
discord.js v13 patch

### PR DESCRIPTION
**Pull request by waki285**
add client intents

### CODE REVIEW

**Comment by Hopefuls** [comment]
This doesn't seem like a change that is required, providing intents on discordjs is optional for the developer. Also why there's not a fully made bot as an example here.

**Comment by waki285** [comment]
> This doesn't seem like a change that is required, providing intents on discordjs is optional for the developer. Also why there's not a fully made bot as an example here.
> 
> Up to xetera in this case though

No, providing an intent for discordjs has been mandatory since v13. Using discordjs without providing an intent will result in an error.

**Comment by link-discord** [comment]
> > This doesn't seem like a change that is required, providing intents on discordjs is optional for the developer. Also why there's not a fully made bot as an example here.
> > 
> > Up to xetera in this case though
> 
> No, providing an intent for discordjs has been mandatory since v13. Using discordjs without providing an intent will result in an error. 

Can confirm

**Comment by Xetera** [comment]
Seems fine to me. If you're looking for code snippets to copy paste, chances are you don't have to worry about the messages intent or anything.

**Comment by jpbberry** [comment]
This also would remove the ability to leave the instantiation generic as the example also works for Eris that does not use the same system.

**Comment by Xetera** [comment]
These docs are meant to just be examples of how to use the SDK. It's infeasible to try to keep up with how every single discord library does its instantiation. You shouldn't be looking at top.gg docs to create your first discord bot

**Pull request merged**
