### PR TITLE
Add deprecation tag

### PR DESCRIPTION
**Pull request by Luke-6723**
Replaces old deprecation with a new one

Example: New deprecation tag

Closes https://github.com/top-gg/docs/issues/45

### CODE REVIEW

**Comment by Xetera** [comment]
Looks nicer with a little more breathing room

**Comment by Xetera** [comment]
I think `5px 8px` is even better. Tried to submit that change with the new vscode editor but it didn't work for some reason lol

**Review by Xetera — APPROVED** [review]

**Comment by Luke-6723** [comment]
Confirmed support for Safari via Browserstack image

**Comment by TiltedKyoso** [comment]
Verified on `Safari Version 15.1 (17612.2.9.1.20)` on my MacBook Pro
Screenshot 2021-11-12 at 10 49 34

**Comment by Luke-6723** [comment]
@Xetera seems to work on Mac that isn't virtualized also, should be good to go

**Pull request merged**
